version: '3.8'

services:
  pg-main:
    image: postgres:16
    network_mode: host
    user: postgres:postgres
    container_name: pg-main
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - pg_main_data:/var/lib/postgresql/data
      - ./pg_configs/master/postgresql.conf:/etc/postgresql/postgresql.conf
      - ./pg_configs/master/pg_hba.conf:/etc/postgresql/pg_hba.conf
      - ./pg_configs/init-master.sh:/docker-entrypoint-initdb.d/init-master.sh
    command: ["-c", "config_file=/etc/postgresql/postgresql.conf", "-c", "hba_file=/etc/postgresql/pg_hba.conf"]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 2s
      timeout: 2s
      retries: 5

  pg-replica:
    image: postgres:16
    network_mode: host
    user: postgres:postgres
    container_name: replica
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - PGPORT=5433
    volumes:
      - pg_replica_data:/var/lib/postgresql/data
      - ./pg_configs/replica/postgresql.conf:/etc/postgresql/postgresql.conf
      - ./pg_configs/replica/pg_hba.conf:/etc/postgresql/pg_hba.conf
      - ./pg_configs/replica/pg_hba_base.conf:/etc/postgresql/pg_hba_base.conf
      - ./pg_configs/init-replica.sh:/docker-entrypoint-initdb.d/init-replica.sh
      - ./pg_configs/replication_monitor_cron.sh:/replication_monitor_cron.sh
    command: ["-c", "config_file=/etc/postgresql/postgresql.conf", "-c", "hba_file=/etc/postgresql/pg_hba.conf"]
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 2s
      timeout: 2s
      retries: 5
    depends_on:
      - pg-main

volumes:
  pg_main_data:
  pg_replica_data:
